export const PolicyReasonCodes = {
  // Hard DENY Codes
  KILL_SWITCH_ACTIVE: 'KILL_SWITCH_ACTIVE',
  CASE_ALREADY_TERMINAL: 'CASE_ALREADY_TERMINAL',
  CASE_NEEDS_REVIEW: 'CASE_NEEDS_REVIEW',
  CUSTOMER_OPTED_OUT: 'CUSTOMER_OPTED_OUT',
  CONTACT_CONSENT_MISSING: 'CONTACT_CONSENT_MISSING',
  HARD_DECLINE_BLOCKS_RETRY: 'HARD_DECLINE_BLOCKS_RETRY',
  MAX_RETRIES_EXCEEDED: 'MAX_RETRIES_EXCEEDED',
  MAX_CONTACTS_EXCEEDED: 'MAX_CONTACTS_EXCEEDED',
  COOLDOWN_VIOLATION: 'COOLDOWN_VIOLATION',
  QUIET_HOURS_VIOLATION: 'QUIET_HOURS_VIOLATION',
  INCOMPATIBLE_ACTION_FOR_RISK: 'INCOMPATIBLE_ACTION_FOR_RISK',
  DUPLICATE_ACTION_IN_FLIGHT: 'DUPLICATE_ACTION_IN_FLIGHT',
  EXPIRED_RECOVERY_WINDOW: 'EXPIRED_RECOVERY_WINDOW',
  REQUIRED_FACTS_MISSING: 'REQUIRED_FACTS_MISSING',

  // REVIEW Codes
  REVIEW_FIRST_MODE: 'REVIEW_FIRST_MODE',
  HIGH_VALUE_CASE: 'HIGH_VALUE_CASE',
  LOW_CONFIDENCE_PROPOSAL: 'LOW_CONFIDENCE_PROPOSAL',
  REPEATED_FAILURES: 'REPEATED_FAILURES',
  BROKEN_PROMISE_TO_PAY: 'BROKEN_PROMISE_TO_PAY',
  AGENT_REQUESTED_REVIEW: 'AGENT_REQUESTED_REVIEW',

  // ALLOW Codes
  POLICY_PASSED_ALLOW: 'POLICY_PASSED_ALLOW',
} as const;

export type PolicyReasonCode = (typeof PolicyReasonCodes)[keyof typeof PolicyReasonCodes];
