import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { approveReview, closeReview, getReview, listReviews, rejectReview, takeOverReview } from '../api/reviews';
import { ErrorState, EmptyState, LoadingState } from '../components/ui/State';
import { formatDate, formatMoney, riskLabel } from '../lib/format';
import type { Review } from '../types/reviews';

export function HumanReviewsPage({ reviewId, navigate }: { reviewId?: string; navigate: (path: string) => void }) {
  const query = useQuery({ queryKey: ['reviews'], queryFn: () => listReviews('PENDING') });
  if (query.isPending) return <LoadingState />; if (query.isError) return <ErrorState message={query.error.message} retry={() => query.refetch()} />;
  if (reviewId) return <ReviewWorkspace reviewId={reviewId} navigate={navigate} />;
  return <div className="space-y-6"><div><p className="eyebrow">HUMAN REVIEW</p><h1 className="page-title">Policy-governed review inbox</h1><p className="page-copy">AI proposes. Deterministic policy requires human intervention only when needed.</p></div>{query.data.reviews.length === 0 ? <EmptyState title="No pending human reviews" detail="Policy-routed work will appear here when operator intervention is required."/> : <div className="space-y-3">{query.data.reviews.map((review) => <button key={review.id} onClick={() => navigate(`/reviews/${review.id}`)} className="card block w-full text-left focus-visible:ring-2"><div className="flex justify-between gap-4"><div><p className="font-semibold">{review.caseId}</p><p className="text-sm text-slate-600">{review.case?.customer?.name || review.case?.customer?.email || 'Customer unavailable'} · {riskLabel(review.case?.riskType || 'PAYMENT_FAILURE')}</p><p className="mt-2 text-sm">{review.reasonForReview}</p></div><div className="text-right text-sm"><b>{review.status}</b><p>{formatMoney(review.case?.amountAtRisk, review.case?.currency)}</p><p className="text-slate-500">{formatDate(review.createdAt)}</p></div></div></button>)}</div>}</div>;
}
function ReviewWorkspace({ reviewId, navigate }: { reviewId:string; navigate:(path:string)=>void }) { const qc=useQueryClient(); const q=useQuery({queryKey:['review',reviewId],queryFn:()=>getReview(reviewId)}); const [notes,setNotes]=useState(''); const [reason,setReason]=useState(''); const [stop,setStop]=useState(false); const m=useMutation({mutationFn:(x:'approve'|'reject'|'takeover'|'close')=>x==='approve'?approveReview(reviewId,notes):x==='reject'?rejectReview(reviewId,reason,notes):x==='takeover'?takeOverReview(reviewId,notes):closeReview(reviewId,reason,stop,notes),onSuccess:()=>{for(const k of [['reviews'],['review',reviewId],['cases'],['revenue-radar-metrics']] as const) void qc.invalidateQueries({queryKey:k});}}); if(q.isPending)return <LoadingState/>;if(q.isError)return <ErrorState message={q.error.message} retry={()=>q.refetch()}/>;const r:Review=q.data.review;return <div className="space-y-5"><button onClick={()=>navigate('/reviews')}>Back to inbox</button><section className="card"><p className="eyebrow">HUMAN APPROVAL REQUIRED BY POLICY</p><h1 className="page-title">Review {r.id}</h1><p>AI proposed this action. Deterministic policy required human review. Approval triggers fresh policy and case-state revalidation before execution.</p><button onClick={()=>navigate(`/recoveries/${r.caseId}`)}>View full case</button></section><section className="card"><h2>Case and proposal</h2><p>{r.caseId} · {r.case?.customer?.name || r.case?.customer?.email} · {formatMoney(r.case?.amountAtRisk,r.case?.currency)}</p><p>{r.reasonForReview}</p><p>{r.planVersion?.proposedActionType || r.action?.actionType}</p><pre>{JSON.stringify(r.planVersion?.proposedActionParams || r.action?.actionParams || {},null,2)}</pre></section><section className="card"><label>Notes<textarea className="input w-full" value={notes} onChange={e=>setNotes(e.target.value)}/></label><label>Reason<textarea className="input w-full" value={reason} onChange={e=>setReason(e.target.value)}/></label><label><input type="checkbox" checked={stop} onChange={e=>setStop(e.target.checked)}/> Close review and stop automated recovery</label><div className="mt-3 flex gap-2"><button disabled={m.isPending} onClick={()=>m.mutate('approve')}>Approve exact proposal</button><button disabled={m.isPending||!reason.trim()} onClick={()=>m.mutate('reject')}>Reject</button><button disabled={m.isPending} onClick={()=>m.mutate('takeover')}>Take over</button><button disabled={m.isPending||!reason.trim()} onClick={()=>m.mutate('close')}>Close review</button></div>{m.isError&&<p role="alert">{(m.error as Error).message}</p>}</section></div>; }
