// @vitest-environment jsdom
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { HumanReviewsPage } from './HumanReviewsPage';
import { ApiError } from '../api/client';
const api = vi.hoisted(() => ({ listReviews: vi.fn(), getReview: vi.fn(), approveReview: vi.fn(), rejectReview: vi.fn(), takeOverReview: vi.fn(), closeReview: vi.fn() }));
vi.mock('../api/reviews', () => api);
const review = { id:'review-1',caseId:'case-1',status:'PENDING',reviewKey:'key',reasonForReview:'Amount requires review',createdAt:'2025-01-01T00:00:00Z',case:{id:'case-1',status:'NEEDS_REVIEW',riskType:'PAYMENT_FAILURE',amountAtRisk:'99.00',currency:'INR',customer:{id:'c',name:'Ada'}},planVersion:{version:1,diagnosisSummary:'Declined',confidence:.9,proposedActionType:'SEND_PAYMENT_LINK',proposedActionParams:{message:'safe'}} };
const view=(node:React.ReactNode)=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}>{node}</QueryClientProvider>);
describe('human review operations',()=>{
 it('renders pending inbox and navigation',async()=>{api.listReviews.mockResolvedValue({reviews:[review]});const nav=vi.fn();view(<HumanReviewsPage navigate={nav}/>);expect(await screen.findByText('Amount requires review')).toBeTruthy();fireEvent.click(screen.getByText('case-1'));expect(nav).toHaveBeenCalledWith('/reviews/review-1');});
 it('renders empty inbox',async()=>{api.listReviews.mockResolvedValue({reviews:[]});view(<HumanReviewsPage navigate={vi.fn()}/>);expect(await screen.findByText('No pending human reviews')).toBeTruthy();});
 it('uses exact mutation endpoints and requires reasons',async()=>{api.getReview.mockResolvedValue({review});api.approveReview.mockResolvedValue({approved:true});api.rejectReview.mockResolvedValue({rejected:true});api.closeReview.mockResolvedValue({closed:true});view(<HumanReviewsPage reviewId="review-1" navigate={vi.fn()}/>);await screen.findByText('Amount requires review');expect((screen.getByText('Reject') as HTMLButtonElement).disabled).toBe(true);fireEvent.change(screen.getByLabelText('Notes'),{target:{value:'review note'}});fireEvent.click(screen.getByText('Approve exact proposal'));await waitFor(()=>expect(api.approveReview).toHaveBeenCalledWith('review-1','review note'));fireEvent.change(screen.getByLabelText('Reason'),{target:{value:'not suitable'}});fireEvent.click(screen.getByText('Reject'));await waitFor(()=>expect(api.rejectReview).toHaveBeenCalledWith('review-1','not suitable','review note'));});
 it('sends canonical status filters and explicit close payloads',async()=>{api.listReviews.mockResolvedValue({reviews:[]});view(<HumanReviewsPage navigate={vi.fn()}/>);await screen.findByText('No pending human reviews');fireEvent.change(screen.getByLabelText('Review status'),{target:{value:'CLOSED'}});await waitFor(()=>expect(api.listReviews).toHaveBeenLastCalledWith('CLOSED'));});
 it('renders specific authority errors',async()=>{for(const [error,text] of [[new ApiError(409,'x',{error:'Stale proposal'}),'Proposal is stale. Refresh the case before taking action.'],[new ApiError(422,'x',{blockedByPolicy:true}),'Approval was blocked by fresh policy revalidation.'],[new ApiError(422,'x',{requiresReview:true}),'Fresh policy still requires human review.'],[new ApiError(403,'x',{}),'Reviewer permission error.'],[new ApiError(409,'x',{error:'changed'}),'This review was already resolved or changed by another operator.']] as const){cleanup();api.getReview.mockResolvedValue({review});api.approveReview.mockRejectedValueOnce(error);view(<HumanReviewsPage reviewId="review-1" navigate={vi.fn()}/>);await screen.findByText('Amount requires review');fireEvent.click(screen.getByText('Approve exact proposal'));expect(await screen.findByText(text)).toBeTruthy();}});
 it('sends takeover and both authoritative close choices',async()=>{api.getReview.mockResolvedValue({review});api.takeOverReview.mockResolvedValue({takenOver:true});api.closeReview.mockResolvedValue({closed:true});view(<HumanReviewsPage reviewId="review-1" navigate={vi.fn()}/>);await screen.findByText('Amount requires review');fireEvent.click(screen.getByText('Take over'));await waitFor(()=>expect(api.takeOverReview).toHaveBeenCalledWith('review-1',''));fireEvent.change(screen.getByLabelText('Reason'),{target:{value:'complete'}});fireEvent.click(screen.getByText('Close review only'));await waitFor(()=>expect(api.closeReview).toHaveBeenCalledWith('review-1','complete',false,''));fireEvent.click(screen.getByText('Close and stop recovery'));await waitFor(()=>expect(api.closeReview).toHaveBeenCalledWith('review-1','complete',true,''));});
});
