import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getPolicy, updatePolicy } from '../api/policy';
import type { PolicyConfig } from '../types/policy';
import { ErrorState, LoadingState } from '../components/ui/State';

type Editable = Pick<PolicyConfig, 'reviewFirstMode' | 'highValueThreshold' | 'minConfidenceThreshold' | 'maxRetriesPerCase' | 'maxContactsPerCase' | 'maxActionsPerCase' | 'cooldownHoursBetweenActions' | 'checkoutAbandonmentThresholdMinutes' | 'quietHoursStart' | 'quietHoursEnd' | 'quietHoursTimezone' | 'maxRecoveryWindowDays' | 'overdueGracePeriodDays'>;
const editable = (policy: PolicyConfig): Editable => ({ reviewFirstMode: policy.reviewFirstMode, highValueThreshold: policy.highValueThreshold, minConfidenceThreshold: policy.minConfidenceThreshold, maxRetriesPerCase: policy.maxRetriesPerCase, maxContactsPerCase: policy.maxContactsPerCase, maxActionsPerCase: policy.maxActionsPerCase, cooldownHoursBetweenActions: policy.cooldownHoursBetweenActions, checkoutAbandonmentThresholdMinutes: policy.checkoutAbandonmentThresholdMinutes, quietHoursStart: policy.quietHoursStart, quietHoursEnd: policy.quietHoursEnd, quietHoursTimezone: policy.quietHoursTimezone, maxRecoveryWindowDays: policy.maxRecoveryWindowDays, overdueGracePeriodDays: policy.overdueGracePeriodDays });

export function PolicySettingsPage() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ['policy'], queryFn: getPolicy });
  const [draft, setDraft] = useState<Editable | null>(null); const [message, setMessage] = useState('');
  useEffect(() => { if (query.data) setDraft(editable(query.data.policy)); }, [query.data]);
  const mutation = useMutation({ mutationFn: (next: Editable) => updatePolicy(next), onSuccess: async () => { await client.invalidateQueries({ queryKey: ['policy'] }); setMessage('Policy settings saved. Server state refreshed.'); }, onError: (error: Error) => setMessage(error.message) });
  if (query.isPending || !draft) return <LoadingState />; if (query.isError) return <ErrorState message={query.error.message} retry={() => query.refetch()} />;
  const original = editable(query.data.policy); const dirty = JSON.stringify(draft) !== JSON.stringify(original);
  const number = (key: Exclude<keyof Editable, 'reviewFirstMode' | 'highValueThreshold' | 'quietHoursTimezone'>, label: string, min: number, max?: number, step?: number) => <label className="block text-sm font-medium text-slate-700">{label}<input min={min} max={max} step={step} type="number" value={draft[key]} onChange={(e) => setDraft({ ...draft, [key]: Number(e.target.value) })} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label>;
  return <div className="max-w-3xl space-y-6"><section><p className="eyebrow">POLICY SETTINGS</p><h1 className="page-title">Deterministic merchant controls</h1><p className="page-copy">Changes are validated server-side and applied only to this merchant.</p></section>
    <section className="card space-y-4"><h2 className="font-semibold">Human review</h2><label className="block text-sm font-medium text-slate-700">High-value review threshold (INR)<input value={draft.highValueThreshold} inputMode="decimal" onChange={(e) => setDraft({ ...draft, highValueThreshold: e.target.value })} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label>{number('minConfidenceThreshold', 'Minimum AI confidence threshold', 0, 1, .01)}<p className="text-xs text-slate-500">AI proposals below this merchant-defined confidence threshold are not automatically trusted. Current value: {Math.round(draft.minConfidenceThreshold * 100)}%.</p><p className="text-xs text-slate-500">Proposals at or above this configured threshold may require human review according to deterministic policy rules.</p><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={draft.reviewFirstMode} onChange={(e) => setDraft({ ...draft, reviewFirstMode: e.target.checked })} /> Review-first mode</label></section>
    <section className="card grid gap-4 sm:grid-cols-2"><h2 className="sm:col-span-2 font-semibold">Contact & retry limits</h2>{number('maxRetriesPerCase', 'Maximum retries', 0)}{number('maxContactsPerCase', 'Maximum contacts', 0)}{number('maxActionsPerCase', 'Maximum actions per case', 1)}{number('cooldownHoursBetweenActions', 'Cooldown hours between actions', 0)}{number('checkoutAbandonmentThresholdMinutes', 'Checkout abandonment minutes', 1)}{number('overdueGracePeriodDays', 'Invoice overdue grace days', 0)}{number('maxRecoveryWindowDays', 'Maximum recovery window (days)', 1)}<p className="text-xs text-slate-500">Autonomous recovery cannot schedule work beyond this case window.</p></section>
    <section className="card grid gap-4 sm:grid-cols-3"><h2 className="sm:col-span-3 font-semibold">Merchant-local quiet hours</h2>{number('quietHoursStart', 'Start hour', 0, 23)}{number('quietHoursEnd', 'End hour', 0, 23)}<label className="block text-sm font-medium text-slate-700">IANA timezone<input value={draft.quietHoursTimezone} onChange={(e) => setDraft({ ...draft, quietHoursTimezone: e.target.value })} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2" /></label><p className="sm:col-span-3 text-xs text-slate-500">Contact actions wait until the next lawful merchant-local time.</p></section>
    <section className="card"><h2 className="font-semibold">Always enforced</h2><ul className="mt-3 space-y-2 text-sm text-slate-600"><li>✓ Customer opt-out always blocks communication.</li><li>✓ Unknown consent cannot authorize communication.</li><li>✓ Fresh policy is re-evaluated before execution.</li><li>✓ Human approval never overrides a hard DENY.</li></ul></section>
    <div className="flex flex-wrap items-center gap-3"><button disabled={!dirty || mutation.isPending} onClick={() => mutation.mutate(draft)} className="rounded-md bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{mutation.isPending ? 'Saving…' : 'Save Changes'}</button><button disabled={!dirty || mutation.isPending} onClick={() => { setDraft(original); setMessage('Changes reset.'); }} className="rounded-md border border-slate-300 px-4 py-2 text-sm font-semibold disabled:opacity-50">Reset changes</button>{dirty && <span className="text-sm text-amber-700">Unsaved changes</span>}{message && <span role="status" className="text-sm text-slate-600">{message}</span>}</div>
  </div>;
}
