import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { listCases } from '../api/cases';
import { RiskBadge, StatusBadge } from '../components/ui/Badge';
import { ErrorState, EmptyState, LoadingState } from '../components/ui/State';
import { formatDate, formatMoney } from '../lib/format';
import type { CaseStatus, RiskType } from '../types/cases';
export function RecoveriesPage({ navigate }: { navigate: (path: string) => void }) {
  const [status, setStatus] = useState<CaseStatus | ''>(''); const [riskType, setRiskType] = useState<RiskType | ''>(''); const [search, setSearch] = useState('');
  const query = useQuery({ queryKey: ['cases', status, riskType], queryFn: () => listCases({ status: status || undefined, riskType: riskType || undefined }) });
  if (query.isPending) return <LoadingState />; if (query.isError) return <ErrorState message={query.error.message} retry={() => query.refetch()} />;
  const cases = query.data.cases.filter((item) => `${item.id} ${item.customer?.name || ''} ${item.customer?.email || ''}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">ACTIVE RECOVERIES</p><h1 className="page-title">Case operations</h1><p className="page-copy">Every row is a tenant-scoped, authoritative recovery case.</p></div></div><div className="card flex flex-wrap gap-3"><input aria-label="Search recoveries" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search case or customer" className="input min-w-52 flex-1" /><select aria-label="Filter by status" value={status} onChange={(event) => setStatus(event.target.value as CaseStatus | '')} className="input"><option value="">All statuses</option>{['OPEN','WAITING','NEEDS_REVIEW','RECOVERED','STOPPED','EXHAUSTED'].map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Filter by risk type" value={riskType} onChange={(event) => setRiskType(event.target.value as RiskType | '')} className="input"><option value="">All risk types</option>{['PAYMENT_FAILURE','SUBSCRIPTION_FAILURE','CHECKOUT_ABANDONMENT','OVERDUE_RECEIVABLE'].map((item) => <option key={item}>{item}</option>)}</select></div>
  {cases.length === 0 ? <EmptyState title="No matching recoveries" detail="No authoritative cases match these filters." /> : <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th>Case / customer</th><th>Risk type</th><th>Amount at risk</th><th>Status</th><th>Next action</th><th>Opened</th></tr></thead><tbody>{cases.map((item) => <tr key={item.id} tabIndex={0} onClick={() => navigate(`/recoveries/${item.id}`)} onKeyDown={(event) => { if (event.key === 'Enter') navigate(`/recoveries/${item.id}`); }} className="cursor-pointer border-b border-slate-100 last:border-0 hover:bg-slate-50 focus:bg-slate-50"><td><p className="font-semibold text-slate-900">{item.id}</p><p className="text-xs text-slate-500">{item.customer?.name || item.customer?.email || 'Customer unavailable'}</p></td><td><RiskBadge risk={item.riskType}/></td><td className="font-medium">{formatMoney(item.amountAtRisk, item.currency)}</td><td><StatusBadge status={item.status}/></td><td className="text-slate-600">{item.actions?.[0]?.actionType?.replaceAll('_',' ') || item.planVersions?.[0]?.proposedActionType?.replaceAll('_',' ') || '—'}</td><td className="text-slate-500">{formatDate(item.openedAt)}</td></tr>)}</tbody></table></div>}</div>;
}
